"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Link, Route, Routes, BrowserRouter as Router } from "react-router-dom";
import React, { lazy } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

const Home = lazy(() => import("@/components/app/Home"));
const Work = lazy(() => import("@/app/work/page"));
const About = lazy(() => import("@/app/about/page"));
const Contact = lazy(() => import("@/app/contact/page"));

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <main>
          <Router>
            <Routes>
              <Route path="/" element={<Navbar2 />}>
                <Route index element={<Home />} />
                <Route path="/work" element={<Work />} />
                <Route path="/about" element={<About />} />
                <Route path="/contact" element={<Contact />} />
              </Route>
            </Routes>
          </Router>
          {children}
        </main>
      </body>
    </html>
  );
}
function Navbar2() {
  return (
    <div className="flex items-center h-[9vh] bg-transparent justify-between px-10 md:px-20">
      <div className="flex gap-x-12">
        <Link to="/">Home</Link>
        <Link to="/work">Work</Link>
        <Link to="/about">About</Link>
        <Link to="/contact">Contact</Link>
      </div>
    </div>
  );
}

export default RootLayout;
